### ISSUE TITLE
how to build the project using the command "mvn clean install -Dmaven.test.skip=true"

### ISSUE THREAD

**Issue by boblam** [esofthead/mycollab#3]
[INFO] mycollab-parent-community ......................... SUCCESS [  5.560 s]
[INFO] mycollab-core ..................................... FAILURE [  5.676 s]
[INFO] mycollab-config ................................... SKIPPED
[INFO] mycollab-localization ............................. SKIPPED
[INFO] mycollab-dao ...................................... SKIPPED
[INFO] mycollab-jackrabbit ............................... SKIPPED
[INFO] mycollab-test ..................................... SKIPPED
[INFO] mycollab-caching .................................. SKIPPED
[INFO] mycollab-services ................................. SKIPPED
[INFO] mycollab-migration ................................ SKIPPED
[INFO] mycollab-server-runner ............................ SKIPPED
[INFO] mycollab-esb ...................................... SKIPPED
[INFO] mycollab-reporting ................................ SKIPPED
[INFO] mycollab-scheduler ................................ SKIPPED
[INFO] mycollab-servlet .................................. SKIPPED
[INFO] mycollab-ui ....................................... SKIPPED
[INFO] mycollab-web ...................................... SKIPPED
[INFO] mycollab-mobile ................................... SKIPPED
[INFO] mycollab-services-community ....................... SKIPPED
[INFO] mycollab-web-community ............................ SKIPPED
[INFO] mycollab-app-community ............................ SKIPPED
[INFO] mycollab-deployer-community ....................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 11.534 s
[INFO] Finished at: 2015-04-12T12:07:27+08:00
[INFO] Final Memory: 16M/40M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.
3:compile (default-compile) on project mycollab-core: Fatal error compiling: inv
alid target release: 1.7 -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal o
rg.apache.maven.plugins:maven-compiler-plugin:3.3:compile (default-compile) on p
roject mycollab-core: Fatal error compiling
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor
.java:216)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor
.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor
.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProje
ct(LifecycleModuleBuilder.java:108)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProje
ct(LifecycleModuleBuilder.java:76)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThre
adedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(Lifecycl
eStarter.java:116)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:361)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:155)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:584)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:213)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:157)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.
java:39)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAcces
sorImpl.java:25)
        at java.lang.reflect.Method.invoke(Method.java:597)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Laun
cher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.jav
a:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(La
uncher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:
356)
Caused by: org.apache.maven.plugin.MojoExecutionException: Fatal error compiling

        at org.apache.maven.plugin.compiler.AbstractCompilerMojo.execute(Abstrac
tCompilerMojo.java:836)
        at org.apache.maven.plugin.compiler.CompilerMojo.execute(CompilerMojo.ja
va:129)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(Default
BuildPluginManager.java:133)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor
.java:208)
        ... 19 more
Caused by: org.codehaus.plexus.compiler.CompilerException: invalid target releas
e: 1.7
        at org.codehaus.plexus.compiler.javac.JavaxToolsCompiler.compileInProces
s(JavaxToolsCompiler.java:172)
        at org.codehaus.plexus.compiler.javac.JavacCompiler.performCompile(Javac
Compiler.java:169)
        at org.apache.maven.plugin.compiler.AbstractCompilerMojo.execute(Abstrac
tCompilerMojo.java:825)
        ... 22 more
Caused by: java.lang.IllegalArgumentException: invalid target release: 1.7
        at com.sun.tools.javac.main.RecognizedOptions$GrumpyHelper.error(Recogni
zedOptions.java:75)
        at com.sun.tools.javac.main.RecognizedOptions$14.process(RecognizedOptio
ns.java:380)
        at com.sun.tools.javac.api.JavacTool.processOptions(JavacTool.java:247)
        at com.sun.tools.javac.api.JavacTool.getTask(JavacTool.java:207)
        at com.sun.tools.javac.api.JavacTool.getTask(JavacTool.java:53)
        at org.codehaus.plexus.compiler.javac.JavaxToolsCompiler.compileInProces
s(JavaxToolsCompiler.java:123)
        ... 24 more
[ERROR]
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please rea
d the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionE
xception
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command

[ERROR]   mvn <goals> -rf :mycollab-core
D:\myProject\mycollab\mycollab-deployer-community>

---------------------------------------------------------------------------------------

i have find the root cause by accessing the url   http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionE
xception.
due to the network ,i can't access the private maven repo for mycollab ?

<pluginRepositories>
        <pluginRepository>
            <id>mycollab-plugin-repo</id>
            <url>https://raw.githubusercontent.com/esofthead/mycollab-maven-repo/master</url>
        </pluginRepository>
    </pluginRepositories>

**Comment by boblam** [comment]
![repo_fail](https://cloud.githubusercontent.com/assets/4026692/7104371/ff84ba00-e10d-11e4-9fb8-d84d459e09df.png)

**Comment by haiphucnguyen** [comment]
Hi boblam,
Check your first error log 'Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.
3:compile (default-compile) on project mycollab-core: Fatal error compiling: inv
alid target release: 1.7 -> [Help 1]'

It seems your maven command uses Java 6. You should check the maven script, and verify the JAVA_HOME environment to make sure at least Java 7 is used to compile MyCollab.

I do not think the issue rely on the private repo, or Github repo. Because we use travis to make the build of MyCollab and it uses the original maven settings. So if travis does not complain about the build, then if your maven is set up properly then it will not complain the MyCollab sources as well :)

But did you try to import MyCollab into Eclipse by following our guideline? Please note that Eclipse is the not recommended for MyCollab so far since it does not support Scala very well, and even we can not make Eclipse compile fast. We suggest you use IntelliJ and we create the new guideline at http://community.mycollab.com/setup-intellij-projects/

**Comment by haiphucnguyen** [comment]
Closed until the poster still have this issue and report back to us.

**Comment by boblam** [comment]
Thanks for the suggesstion and support.
I have update the jdk from 1.6 to 1.7 and it works fine.

Another issue,when first time i try to setup with the Intellij IDE ,i can't run the application and it also pop some error message.I also try to reference the solutions at http://stackoverflow.com/questions/17300318/error-in-intellij-idea-hello-world-program but not work.


![run_configuration_error](https://cloud.githubusercontent.com/assets/4026692/7129605/1571b448-e295-11e4-87c3-e688d1148c90.png)
![application_configuration](https://cloud.githubusercontent.com/assets/4026692/7129608/1fec97ee-e295-11e4-8c98-643faa137f79.png)

![project_setting](https://cloud.githubusercontent.com/assets/4026692/7129609/247f99be-e295-11e4-8617-6912828c45ea.png)

**Comment by haiphucnguyen** [comment]
Could you please select **Build > Rebuild project** then run the application again. Thanks for your detail report, and I do not see any issue. The possible error is the make process is not completed but IntelliJ does not refresh the whole sources. This is the very rare case in IntelliJ but it happens many times in Eclipse made us drop to use Eclipse to develop MyCollab.

**Comment by boblam** [comment]
After i restart the Intellij IDE and rebuild projects,it pops error info again.

![rebuild](https://cloud.githubusercontent.com/assets/4026692/7130048/24444a6a-e29c-11e4-8f5d-4b227a1c2670.png)

**Comment by haiphucnguyen** [comment]
You get the latest code again, since this is the issue of a library assertj-core, it just work for java 8. We have downgrade the version of this library to 2.0.0, and it works well for java 7

**Comment by boblam** [comment]
Hi haiphucnguyen ,after running the application and setup info on installation page succefully,it pops some info to tell me to redirect to app and lead me to "Directory" folder not the MyCollab site.
![redirect](https://cloud.githubusercontent.com/assets/4026692/7153145/1b7c7e8c-e37a-11e4-8c7a-7a6beeb66869.png)

**Comment by haiphucnguyen** [comment]
My developer did check the installation process, and it works well. I guess that there is an exception during running MyCollab, could you give me the console log or file log MyCollab output?

We try to simplify the installation process over than other open source product, and we are happy to support you in this case. Thank you.

**Comment by boblam** [comment]
I have sent the MyCollab output file to your email  hainguyen@esofthead.com

**Comment by haiphucnguyen** [comment]
Thank you. I just replied to you. Please help me to check it again.

**Comment by haiphucnguyen** [comment]
This issue is resolved. It only happen if you run MyCollab in the IDE on Windows.

**Comment by haiphucnguyen** [comment]
Please get the latest sources and run the MyCollab again. Thank you.

**Comment by boblam** [comment]
I will try it  tomorrow. Thanks.

**Comment by boblam** [comment]
Now i can run the project MyCollab on my windows computer.Thanks for high efficiency support.

**Comment by mmghasemi** [comment]
Hi,
How can i compile project without ant IDE? with mvn clean install ?

**Comment by haiphucnguyen** [comment]
Here you go https://community.mycollab.com/docs/developing-mycollab/create-the-mycollab-installer/
